/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author jesus
 */
public class InicioView extends javax.swing.JFrame {

   private javax.swing.Timer parpadeoTimer; // Referencia al temporizador

    public InicioView() {
        initComponents();

        ajustarImagenes(); // Ajustar imágenes al tamaño de los labels
        iniciarAnimacionParpadeo(); // Animación de parpadeo
        agregarEventoClic(); // Hacer clickeable lblPressStart
    }

    private void ajustarImagenes() {
        lblPressStart.setIcon(resizeImage("/images/Press_Start.png", lblPressStart.getWidth(), lblPressStart.getHeight()));
        lblTitulo.setIcon(resizeImage("/images/Titulo.png", lblTitulo.getWidth(), lblTitulo.getHeight()));
        jLabel1.setIcon(resizeImage("/images/PantallaInicio.jpg", jLabel1.getWidth(), jLabel1.getHeight()));

        btnCrearPartida.setVisible(false);
        btnUnirsePartida.setVisible(false);
    }

    private ImageIcon resizeImage(String path, int width, int height) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    private void iniciarAnimacionParpadeo() {
        parpadeoTimer = new javax.swing.Timer(500, e -> {
            lblPressStart.setVisible(!lblPressStart.isVisible());
        });
        parpadeoTimer.start();
    }

    private void agregarEventoClic() {
        lblPressStart.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detenerParpadeo(); // Detener la animación
                lblPressStart.setVisible(false); // Oculta el lblPressStart
                mostrarBotones(); // Muestra los botones
            }
        });
    }

    private void detenerParpadeo() {
        if (parpadeoTimer != null && parpadeoTimer.isRunning()) {
            parpadeoTimer.stop(); // Detener el temporizador
        }
    }

    private void mostrarBotones() {
        btnCrearPartida.setVisible(true);
        btnUnirsePartida.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agrupador = new javax.swing.JPanel();
        btnUnirsePartida = new javax.swing.JButton();
        btnCrearPartida = new javax.swing.JButton();
        lblPressStart = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Agrupador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUnirsePartida.setBackground(new java.awt.Color(204, 204, 204));
        btnUnirsePartida.setForeground(new java.awt.Color(0, 0, 0));
        btnUnirsePartida.setText("Unirse Partida");
        btnUnirsePartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirsePartidaActionPerformed(evt);
            }
        });
        Agrupador.add(btnUnirsePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 170, 60));

        btnCrearPartida.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearPartida.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearPartida.setText("Crear Partida");
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        Agrupador.add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 170, 60));

        lblPressStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Press_Start.png"))); // NOI18N
        Agrupador.add(lblPressStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 340, 160));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Titulo.png"))); // NOI18N
        Agrupador.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 600, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PantallaInicio.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        Agrupador.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Agrupador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Agrupador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void btnUnirsePartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirsePartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUnirsePartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agrupador;
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnUnirsePartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPressStart;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
